services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '49497:27017'
    volumes:
      - mongodbworkout_data:/data/db
volumes:
  mongodbworkout_data:  # <--- Define the volume
